language: r

warnings_are_errors: false

before_install:
  - cp ./build/DESCRIPTION ./pkg
  - cd ./pkg

sudo: required

apt_packages:
  - libv8-dev

notifications:
  email:
    on_success: change
    on_failure: change

